### ISSUE TITLE
Fresh install - ambiguous import

### ISSUE THREAD

**Issue by bstanescu** [danielvladco/go-proto-gql#30]
Tried a fresh install:

`go version go1.16.3 darwin/amd64`

```sh
➜  go install github.com/danielvladco/go-proto-gql/protoc-gen-gql

no required module provides package github.com/danielvladco/go-proto-gql/protoc-gen-gql; to add it:
    go get github.com/danielvladco/go-proto-gql/protoc-gen-gql

➜   go get github.com/danielvladco/go-proto-gql/protoc-gen-gql

go: downloading github.com/vektah/gqlparser v1.3.1
github.com/danielvladco/go-proto-gql/protoc-gen-gql imports
    github.com/danielvladco/go-proto-gql/pkg/generator imports
    github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
    github.com/danielvladco/go-proto-gql v0.8.3 (~/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.3/pb)
    github.com/danielvladco/go-proto-gql/pb v0.6.0 (~/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.0)
```

Setting `GO111MODULE` to off works as expected:
```sh
GO111MODULE=off go get -v \
    github.com/danielvladco/go-proto-gql/protoc-gen-gql \
    github.com/danielvladco/go-proto-gql/protoc-gen-gogql
```

**Comment by danielvladco** [comment]
Use these commands to install the tool
```
go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@latest
go install github.com/danielvladco/go-proto-gql/protoc-gen-gogql
```

**Comment by bstanescu** [comment]
Thanks, but I get the same error 🤷

```sh
➜ go clean -modcache

➜ go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@latest

go: downloading github.com/danielvladco/go-proto-gql v0.8.3
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/protobuf v1.26.0
go: downloading github.com/danielvladco/go-proto-gql/pb v0.6.0
go: downloading github.com/jhump/protoreflect v1.8.2
go: downloading github.com/vektah/gqlparser v1.3.1
go: downloading github.com/vektah/gqlparser/v2 v2.1.0
go: downloading github.com/danielvladco/go-proto-gql/pb v0.6.1
github.com/danielvladco/go-proto-gql/protoc-gen-gogql imports
	github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.3 (~/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.3/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.0 (~/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.0)
```

Maybe worth mentioning that I run the command outside the GOPATH? It used to work as described in the readme prior to the latest changes.

I want to point out that `GO111MODULE=off` solution in the OP worked for me.

**Comment by danielvladco** [comment]
Yeah, I know, the thing is I implemented some new features that depend on my fork of `github.com/99designs/gqlgen` and for this I needed the replace statement...

This is why now you need to install it differently.

However the issue you see is for a different reason, probably you have some old sums in your go.sum

check this issue https://github.com/danielvladco/go-proto-gql/issues/25

**Comment by bstanescu** [comment]
I have already checked go.sum (it had no reference to gqlgen or go-proto-gql).
Thanks for the cross reference to issue #25 (hadn't noticed it).  

Maybe worth updating README.md ?

Closing this as it's not really an issue at the moment for me.

Thanks for your swift support! ⭐

**Comment by gurre** [comment]
I get this issue too.

The import in the generated `service.pb.go` does not resolve to the newest version. Go mod is for some reason unable to find the package.
```go
// service.pb.go
_ "github.com/danielvladco/go-proto-gql/pb"
// ...
```
It does resolve to v0.6.1 but that then leads to `Import "pb/graphql.proto" was not found or had errors.` or `ambiguous import` error . The later error happens when both versions are added.

```
github.com/... imports
	github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.3 (/Users/user/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.3/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.1 (/Users/user/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.1)
```

It seems like go modules are broken with this package. I'm not able to use it with the newest version. There is a workaround to get it to compile at least:
```
git clone https://github.com/danielvladco/go-proto-gql vendor/github.com/danielvladco/go-proto-gql
```

**Comment by gurre** [comment]
I managed to get it to work on `go version go1.17.2 darwin/amd64`:
```
$ go mod tidy
github.com/... imports
	github.com/danielvladco/go-proto-gql/pb loaded from github.com/danielvladco/go-proto-gql@v0.8.3,
	but go 1.16 would fail to locate it:
	ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.3 (/Users/user/Dev/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.3/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.1 (/Users/user/Dev/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.1)

To proceed despite packages unresolved in go 1.16:
	go mod tidy -e
If reproducibility with go 1.16 is not needed:
	go mod tidy -compat=1.17
For other options, see:
	https://golang.org/doc/modules/pruning
```
Continue without reproducibility with GO 1.16
```shell
$ go mod tidy -compat=1.17
$ go mod vendor
```
